language: node_js
node_js:
  - 0.10
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
before_script:
  - "java -jar selenium-server-standalone-2.47.0.jar > /dev/null &"
  - "npm run w > /dev/null &"
  - sleep 5
after_success:
  - npm run coveralls
